version: '3'

services:
  app:
    container_name: 'challenge-node'
    build: .
    command: 'npm start'
    depends_on: 
      - 'db'
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app'
  db:
    container_name: 'challenge-mongo'
    image: 'mongo'
    ports:
      - '27017:27017'